version: '3'
services:
  db:
    image: postgres
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
  app:
    build: .
    tty: true
    stdin_open: true
    container_name: my_app
    command: bash -c "rm -f tmp/pids/server.pid && bin/rake db:create db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ".:/var/www"
    ports:
      - "3000:3000"
    depends_on:
      - db
